global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "parser"
    static_configs:
      - targets: ["parser:9101"]

  - job_name: "sender"
    static_configs:
      - targets: ["sender:9102"]

